In [2]:
import time # for timing training of data
import pandas as pd
import numpy as np
from sklearn.svm import SVC # actual support vector classifier
from sklearn.model_selection import train_test_split # for splitting dataset

import imblearn
from imblearn.over_sampling import SMOTE
from collections import Counter
from sklearn.model_selection import RepeatedKFold, RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score

In [3]:
# load cleaned up csvs into dataframe
path = 'cleaned_data/receivedOffer/receivedOffer_' #receivedOffer/receivedOffer_' # allStudents/allStudents_
years = [11,12,13,14,15,16, 17]
target = 'ACCEPTED'

df = pd.read_csv(path + '10.csv') # one of the years that'll be used for training

# add more data to train on
for y in years:
    df = df.append(pd.read_csv(path + str(y)+'.csv'))
    
print('Total students: ' + str(len(df)))
print(len(df))
df.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True) #dropping all rows that contain an empty value
print(len(df))
print(len(df.ACCEPTED))

df_tgt = df.ACCEPTED #get 1d array as the target
df = df.drop(['ACCEPTED'], axis='columns')
df = df.drop(['ZIP3'], axis='columns') # temporary

print('...')
#X_train, X_test, y_train, y_test = train_test_split(df_train, df_train_tgt, test_size=0.2) # 80% test and 20% training
#print(len(X_train))
#print(len(y_train))
#print(len(X_test))
#print(len(y_test))
print(df_tgt.value_counts()) # 23% of students offered admission didn't accept 

Total students: 7668
7668
7531
7531
...
1    6115
0    1416
Name: ACCEPTED, dtype: int64


In [4]:
print(df_tgt.value_counts())
oversample = SMOTE()
df, df_tgt = oversample.fit_resample(df, df_tgt)
print(df_tgt.value_counts())
X_train, X_test, y_train, y_test = train_test_split(df, df_tgt, test_size=0.2) # 80% test and 20% training

1    6115
0    1416
Name: ACCEPTED, dtype: int64
1    6115
0    6115
Name: ACCEPTED, dtype: int64


In [ ]:
start = time.time()
model = SVC(kernel = 'linear', verbose=True, class_weight='balanced')# C=10, gamma=10)
model.fit(X_train, y_train) # call fit method to train your model
end = time.time()
print("Time taken in seconds: " + str(end - start))
print(model.score(X_test, y_test)) # tests model accuracy
resultArray = model.predict(X_test)
print(resultArray)
unique, counts = np.unique(resultArray, return_counts=True)
print(dict(zip(unique, counts)))
print(model)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores = cross_val_score(model, df, df_tgt, scoring='roc_auc', cv=cv, n_jobs=-1)
print('Mean ROC AUC: %.3f' % mean(scores))

In [584]:
# scatter plot of examples by class label
import matplotlib.pyplot as pyplot
counter_items = [0,1]
for label in range(1):
    row_ix = (df_tgt == label)[0]
    pyplot.scatter(df[row_ix, 0], df[row_ix, 1], label=str(label))
pyplot.legend()
pyplot.show()

TypeError: '(0    False
0    False
0    False
0    False
0    False
0    False
0     True
0    False
Name: ACCEPTED, dtype: bool, 0)' is an invalid key

In [563]:
print('DONE')

DONE


In [499]:
# load cleaned up csvs into dataframe
path = 'cleaned_data/receivedOffer/receivedOffer_' #receivedOffer/receivedOffer_' # allStudents/allStudents_
years = [11,12,13,14,15,16] # 17 <- used for testing created model
target = 'ACCEPTED'

df_test = pd.read_csv(path + '17.csv')
df_train = pd.read_csv(path + '10.csv') # one of the years that'll be used for training

# add more data to train on
for y in years:
    #print(' + Year: ' + str(y) + ' = ')
    df_train = df_train.append(pd.read_csv(path + str(y)+'.csv'))
    
print('Total students: ' + str(len(df_train)))

#maybe combining and scrambling the data and splitting the data 80-20 for training and testing would be better?
#so "from sklearn.model_selection import train_test_split"?

#32710 students --> 28446 students after removing students with any empty fields

Total students: 6557


In [500]:
print(len(df_train))
df_train.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True) #dropping all rows that contain an empty value
df_test.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True) #dropping all rows that contain an empty value
print(len(df_train))
print(len(df_train.ACCEPTED))

6557
6450
6450


In [501]:
#dir(df_train)
df_train_tgt=df_train.ACCEPTED #get 1d array as the target
df_test_tgt=df_test.ACCEPTED

# drop target columns from datasets
#df_train.head()
df_train = df_train.drop(['ACCEPTED'], axis='columns')
df_train = df_train.drop(['ZIP3'], axis='columns') # temporary
df_test = df_test.drop(['ACCEPTED'], axis='columns')
df_test = df_test.drop(['ZIP3'], axis='columns') # temporary

#df_test.head()
print(len(df_train))
#print(len(df_train.ACCEPTED))
print(len(df_train_tgt))

6450
6450


In [502]:
from sklearn.model_selection import train_test_split # for splitting dataset
X_train, X_test, y_train, y_test = train_test_split(df_train, df_train_tgt, test_size=0.2) # 80% test and 20% training

In [503]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

model = SVC(kernel = 'rbf', C=10, gamma=10)
model.fit(X_train, y_train)
print(model.predict(X_test))
print(model.score(X_test, y_test))

5160
5160
1290
1290
[1 1 1 ... 1 1 1]
0.8


In [504]:
model2 = SVC(verbose=True, kernel='linear') #, gamma=1000, C=10) #decision_function_shape='ovo', class_weight={0: 606, 1: 2619}, gamma='auto', class_weight={0: 202, 1: 873}
start2 = time.time()
model2.fit(X_train, y_train) # call fit method to train your model
end2 = time.time()
print(model2.score(X_test, y_test)) # tests model accuracy
print("Time taken in seconds: " + str(end2 - start2))

[LibSVM]0.813953488372093
Time taken in seconds: 5.074544191360474


In [505]:
print(df_train_tgt.value_counts()) # 23% of all student data is students that have accepted offers... 
# was all data of students that were offered admission?

1    5238
0    1212
Name: ACCEPTED, dtype: int64


In [507]:
print(model2)
#len(df_train)
resultArray = model2.predict(X_test)
print(resultArray)
unique, counts = np.unique(resultArray, return_counts=True)
dict(zip(unique, counts))

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=True)
[1 1 1 ... 1 1 1]


{0: 44, 1: 1246}

In [491]:
len(df_test)

1081

In [492]:
df_train.head()

GEND  SCHOOL  CONFUNI  CONFCHOIC  WAVERG2        AVG  PREF     DIST
0   120   11219    196.0        2.0      843  84.333333     2   82.268
1   119   10711    196.0        1.0      970  96.333333     1  120.785
2   120   11199    196.0        3.0      863  86.333333     3    5.061
3   120   11160    196.0        3.0      865  86.500000     3   85.743
4   120   10503    196.0        2.0      900  88.000000     2   78.822

In [493]:
model = SVC(verbose=True) #, class_weight='balanced')
start = time.time()
model.fit(df_train, df_train_tgt)
end = time.time()
print("Time taken in seconds: " + str(end - start))

# parameter changing to be done here
# fixme: get progress to show in some way upon execution
# takes about 15 minutes to run

[LibSVM]Time taken in seconds: 0.7495152950286865


In [497]:
model.score(df_test, df_test_tgt)
resultArray = model.predict(df_test)
print(resultArray)
unique, counts = np.unique(resultArray, return_counts=True)
dict(zip(unique, counts))

[1 1 1 ... 1 1 1]


{1: 1081}

In [68]:
print(model)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=True)
